flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/peterbecich/fp-course.git
    commit: b2965c233acdf1a97667a67d2e8cdb425551144f
  extra-dep: true

#    git: git@github.com:peterbecich/fp-course.git  
extra-deps: [base-4.9.1.0, template-haskell-2.11.1.0, text-1.2.2.1, uuid-1.3.13, random-1.1, mtl-2.2.1, containers-0.5.8.2, lens-4.15.1, scotty-0.11.0, either-4.4.1.1, trifecta-1.6.2.1, parsers-0.12.4, checkers-0.4.6, concurrent-extra-0.7.0.10]
# resolver: lts-8.5
# resolver: lts-7.19
# resolver: lts-6.30
resolver: lts-8.8
