flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/peterbecich/fp-course.git
    commit: 997f4e353727bfadd822476a907021711171b20d
  extra-dep: true

#    git: git@github.com:peterbecich/fp-course.git  
extra-deps: [template-haskell-2.11.1.0, text-1.2.2.1, uuid-1.3.13, random-1.1, mtl-2.2.1, containers-0.5.8.2, lens-4.15.1, scotty-0.11.0, either-4.4.1.1]
resolver: lts-8.5
#resolver: lts-7.19
# resolver: lts-6.30
