flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/peterbecich/fp-course.git
    commit: 860e416681f92f5a477d027e3b511f9e355f2370
  extra-dep: true

#    git: git@github.com:peterbecich/fp-course.git  
extra-deps: [template-haskell-2.11.1.0, text-1.2.2.1, uuid-1.3.13]
# resolver: lts-8.4
#resolver: lts-7.19
resolver: lts-6.30
